export enum MatchSourceType {
  SUHANA = 'SUHANA',
  FAMILY = 'FAMILY',
  RELATIVE = 'RELATIVE',
  FRIEND = 'FRIEND',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  OTHER_MATRIMONY = 'OTHER_MATRIMONY',
  WORKPLACE = 'WORKPLACE',
  COMMUNITY = 'COMMUNITY',
  OTHER = 'OTHER',
}
