export enum FeedbackCategory {
  WEBSITE_EXPERIENCE = 'WEBSITE_EXPERIENCE',
  PROFILE_MATCHING = 'PROFILE_MATCHING',
  MESSAGING = 'MESSAGING',
  AI_MATCHMAKING = 'AI_MATCHMAKING',
  PREMIUM_BILLING = 'PREMIUM_BILLING',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
  FEATURE_REQUEST = 'FEATURE_REQUEST',
  BUG_REPORT = 'BUG_REPORT',
  SUGGESTION = 'SUGGESTION',
  COMPLAINT = 'COMPLAINT',
  MOBILE_EXPERIENCE = 'MOBILE_EXPERIENCE',
  SAFETY_SECURITY = 'SAFETY_SECURITY',
  PRIVACY_ACCOUNT = 'PRIVACY_ACCOUNT',
  SUCCESS_STORY = 'SUCCESS_STORY',

  // Profile-specific feedback
  PROFILE_POSITIVE = 'PROFILE_POSITIVE',
  PROFILE_NEGATIVE = 'PROFILE_NEGATIVE',
  PROFILE_REPORT = 'PROFILE_REPORT',

  OTHER = 'OTHER',
}

export const GENERAL_CATEGORIES: FeedbackCategory[] = [
  FeedbackCategory.BUG_REPORT,
  FeedbackCategory.PROFILE_MATCHING,
  FeedbackCategory.FEATURE_REQUEST,
  FeedbackCategory.CUSTOMER_SUPPORT,
  FeedbackCategory.COMPLAINT,
  FeedbackCategory.MESSAGING,
  FeedbackCategory.SUGGESTION,
  FeedbackCategory.WEBSITE_EXPERIENCE,
  FeedbackCategory.PREMIUM_BILLING,
  FeedbackCategory.MOBILE_EXPERIENCE,
  FeedbackCategory.AI_MATCHMAKING,
  FeedbackCategory.SAFETY_SECURITY,
  FeedbackCategory.SUCCESS_STORY,
];

export const PROFILE_CATEGORIES: FeedbackCategory[] = [
  FeedbackCategory.PROFILE_POSITIVE,
  FeedbackCategory.PROFILE_NEGATIVE,
  FeedbackCategory.PROFILE_REPORT,
];
