// All meaningful, trackable user actions across the Suhana platform.
// Values are stored verbatim in audit_log.event_type — keep them stable.
export enum AuditEventType {
  // ── Account ──────────────────────────────────────────────────────────────
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  ACCOUNT_UPDATED = 'ACCOUNT_UPDATED',
  ACCOUNT_DEACTIVATED = 'ACCOUNT_DEACTIVATED',
  ACCOUNT_REACTIVATED = 'ACCOUNT_REACTIVATED',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  EMAIL_CHANGED = 'EMAIL_CHANGED',
  MOBILE_CHANGED = 'MOBILE_CHANGED',

  // ── Profile ──────────────────────────────────────────────────────────────
  PROFILE_CREATED = 'PROFILE_CREATED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  PROFILE_COMPLETED = 'PROFILE_COMPLETED',
  PROFILE_REOPENED = 'PROFILE_REOPENED',

  // Identity-sensitive field changes (used by red-flag / trust scoring)
  PROFILE_NAME_CHANGED = 'PROFILE_NAME_CHANGED',
  PROFILE_DOB_CHANGED = 'PROFILE_DOB_CHANGED',
  PROFILE_GENDER_CHANGED = 'PROFILE_GENDER_CHANGED',
  PROFILE_RELIGION_CHANGED = 'PROFILE_RELIGION_CHANGED',
  PROFILE_CASTE_CHANGED = 'PROFILE_CASTE_CHANGED',
  PROFILE_EDUCATION_CHANGED = 'PROFILE_EDUCATION_CHANGED',
  PROFILE_OCCUPATION_CHANGED = 'PROFILE_OCCUPATION_CHANGED',
  PROFILE_LOCATION_CHANGED = 'PROFILE_LOCATION_CHANGED',

  // ── Profile photos ───────────────────────────────────────────────────────
  PROFILE_PHOTO_ADDED = 'PROFILE_PHOTO_ADDED',
  PROFILE_PHOTO_UPDATED = 'PROFILE_PHOTO_UPDATED',
  PROFILE_PHOTO_DELETED = 'PROFILE_PHOTO_DELETED',
  PROFILE_PHOTO_SET_PRIMARY = 'PROFILE_PHOTO_SET_PRIMARY',

  // ── Gallery photos ───────────────────────────────────────────────────────
  GALLERY_PHOTO_ADDED = 'GALLERY_PHOTO_ADDED',
  GALLERY_PHOTO_UPDATED = 'GALLERY_PHOTO_UPDATED',
  GALLERY_PHOTO_DELETED = 'GALLERY_PHOTO_DELETED',

  // ── Partner preferences ──────────────────────────────────────────────────
  PARTNER_PREFERENCE_CREATED = 'PARTNER_PREFERENCE_CREATED',
  PARTNER_PREFERENCE_UPDATED = 'PARTNER_PREFERENCE_UPDATED',

  // ── Matchmaking ──────────────────────────────────────────────────────────
  PROFILE_VIEWED = 'PROFILE_VIEWED',
  SHORTLISTED = 'SHORTLISTED',
  SHORTLIST_REMOVED = 'SHORTLIST_REMOVED',
  INTEREST_SENT = 'INTEREST_SENT',
  INTEREST_ACCEPTED = 'INTEREST_ACCEPTED',
  INTEREST_REJECTED = 'INTEREST_REJECTED',
  MATCH_FIXED = 'MATCH_FIXED',
  MATCH_FIXED_CANCELLED = 'MATCH_FIXED_CANCELLED',

  // ── Communication ────────────────────────────────────────────────────────
  CHAT_STARTED = 'CHAT_STARTED',
  MESSAGE_SENT = 'MESSAGE_SENT',
  VOICE_CALL_REQUESTED = 'VOICE_CALL_REQUESTED',
  VIDEO_CALL_REQUESTED = 'VIDEO_CALL_REQUESTED',

  // ── Membership ───────────────────────────────────────────────────────────
  PLAN_PURCHASED = 'PLAN_PURCHASED',
  PLAN_UPGRADED = 'PLAN_UPGRADED',
  PLAN_DOWNGRADED = 'PLAN_DOWNGRADED',
  PLAN_RENEWED = 'PLAN_RENEWED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  // ── Safety ───────────────────────────────────────────────────────────────
  PROFILE_REPORTED = 'PROFILE_REPORTED',
  PROFILE_BLOCKED = 'PROFILE_BLOCKED',
  PROFILE_UNBLOCKED = 'PROFILE_UNBLOCKED',

  // ── Login ────────────────────────────────────────────────────────────────
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',

  // ── Trust & Testimonials ───────────────────────────────────────────────────
  REVIEW_CREATED = 'REVIEW_CREATED',
  REVIEW_UPDATED = 'REVIEW_UPDATED',
  REVIEW_APPROVED = 'REVIEW_APPROVED',
  REVIEW_REJECTED = 'REVIEW_REJECTED',
  REVIEW_FEATURED = 'REVIEW_FEATURED',
  REVIEW_REPORTED = 'REVIEW_REPORTED',
  REVIEW_REPLY_ADDED = 'REVIEW_REPLY_ADDED',
  SUCCESS_STORY_CREATED = 'SUCCESS_STORY_CREATED',
  SUCCESS_STORY_APPROVED = 'SUCCESS_STORY_APPROVED',
  SUCCESS_STORY_MARRIAGE_VERIFIED = 'SUCCESS_STORY_MARRIAGE_VERIFIED',
}
