-- =============================================================================
-- Aurora Personality Assessment — MySQL 8 DDL + seed data
--
-- Mirrors migrations 1784333900000-create-personality-assessment and
-- 1784334000000-seed-personality-questions. Prefer the migrations
-- (DB_MIGRATIONS_RUN=true); use this script for manual/DBA provisioning.
-- The seed section is generated from src/modules/personality/seed/personality-question-bank.ts.
--
-- Scoring: each option adds score_value points to score_direction.
--   Strongly Agree → keyed pole +2 · Agree → +1 · Neutral → 0
--   Disagree → opposite pole +1 · Strongly Disagree → opposite pole +2
-- =============================================================================

CREATE TABLE IF NOT EXISTS `personality_questions` (
  `id`            int                         NOT NULL AUTO_INCREMENT,
  `question_code` varchar(20)                 NOT NULL,
  `question_text` varchar(500)                NOT NULL,
  `dimension`     enum('EI','SN','TF','JP')   NOT NULL,
  `translations`  json                        NULL,
  `active_flag`   tinyint                     NOT NULL DEFAULT 1,
  `display_order` int                         NOT NULL,
  `created_at`    datetime(6)                 NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at`    datetime(6)                 NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_PERSONALITY_QUESTIONS_CODE` (`question_code`),
  KEY `IDX_PERSONALITY_QUESTIONS_ACTIVE_ORDER` (`active_flag`, `display_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `personality_question_options` (
  `id`              int                                       NOT NULL AUTO_INCREMENT,
  `question_id`     int                                       NOT NULL,
  `option_key`      varchar(30)                               NOT NULL,
  `option_text`     varchar(100)                              NOT NULL,
  `score_direction` enum('E','I','S','N','T','F','J','P')     NOT NULL,
  `score_value`     tinyint unsigned                          NOT NULL,
  `display_order`   tinyint unsigned                          NOT NULL,
  `translations`    json                                      NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_PERSONALITY_OPTIONS_QUESTION_KEY` (`question_id`, `option_key`),
  CONSTRAINT `FK_PERSONALITY_OPTIONS_QUESTION` FOREIGN KEY (`question_id`)
    REFERENCES `personality_questions` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `personality_assessments` (
  `id`                 varchar(36)                         NOT NULL,
  `profile_id`         varchar(36)                         NOT NULL,
  `status`             enum('IN_PROGRESS','COMPLETED')     NOT NULL DEFAULT 'IN_PROGRESS',
  `completed_date`     datetime                            NULL,
  `personality_type`   char(4)                             NULL,
  `confidence_score`   decimal(5,2)                        NULL,
  `introversion_score` smallint unsigned                   NOT NULL DEFAULT 0,
  `extroversion_score` smallint unsigned                   NOT NULL DEFAULT 0,
  `sensing_score`      smallint unsigned                   NOT NULL DEFAULT 0,
  `intuition_score`    smallint unsigned                   NOT NULL DEFAULT 0,
  `thinking_score`     smallint unsigned                   NOT NULL DEFAULT 0,
  `feeling_score`      smallint unsigned                   NOT NULL DEFAULT 0,
  `judging_score`      smallint unsigned                   NOT NULL DEFAULT 0,
  `perceiving_score`   smallint unsigned                   NOT NULL DEFAULT 0,
  `created_at`         datetime(6)                         NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at`         datetime(6)                         NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `IDX_PERSONALITY_ASSESSMENTS_PROFILE_STATUS` (`profile_id`, `status`, `completed_date`),
  KEY `IDX_PERSONALITY_ASSESSMENTS_TYPE` (`personality_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `personality_responses` (
  `id`                 varchar(36)  NOT NULL,
  `assessment_id`      varchar(36)  NOT NULL,
  `question_id`        int          NOT NULL,
  `selected_option_id` int          NOT NULL,
  `created_at`         datetime(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_PERSONALITY_RESPONSES_ASSESSMENT_QUESTION` (`assessment_id`, `question_id`),
  CONSTRAINT `FK_PERSONALITY_RESPONSES_ASSESSMENT` FOREIGN KEY (`assessment_id`)
    REFERENCES `personality_assessments` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `FK_PERSONALITY_RESPONSES_QUESTION` FOREIGN KEY (`question_id`)
    REFERENCES `personality_questions` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION,
  CONSTRAINT `FK_PERSONALITY_RESPONSES_OPTION` FOREIGN KEY (`selected_option_id`)
    REFERENCES `personality_question_options` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- Seed: 32 questions (8 per dimension, interleaved display order)
-- -----------------------------------------------------------------------------
INSERT INTO `personality_questions`
  (`id`, `question_code`, `question_text`, `dimension`, `active_flag`, `display_order`)
VALUES
  (1, 'EI_01', 'I enjoy being the center of attention.', 'EI', 1, 1),
  (2, 'EI_02', 'Social gatherings energize me.', 'EI', 1, 5),
  (3, 'EI_03', 'I prefer discussing ideas with others.', 'EI', 1, 9),
  (4, 'EI_04', 'I make friends quickly.', 'EI', 1, 13),
  (5, 'EI_05', 'I enjoy networking events.', 'EI', 1, 17),
  (6, 'EI_06', 'I think aloud when solving problems.', 'EI', 1, 21),
  (7, 'EI_07', 'I like group activities.', 'EI', 1, 25),
  (8, 'EI_08', 'I initiate conversations easily.', 'EI', 1, 29),
  (9, 'SN_01', 'I focus on practical facts.', 'SN', 1, 2),
  (10, 'SN_02', 'I trust experience more than instinct.', 'SN', 1, 6),
  (11, 'SN_03', 'I prefer concrete examples.', 'SN', 1, 10),
  (12, 'SN_04', 'I notice small details.', 'SN', 1, 14),
  (13, 'SN_05', 'I enjoy step-by-step processes.', 'SN', 1, 18),
  (14, 'SN_06', 'I value proven methods.', 'SN', 1, 22),
  (15, 'SN_07', 'I focus on present realities.', 'SN', 1, 26),
  (16, 'SN_08', 'I prefer realistic plans.', 'SN', 1, 30),
  (17, 'TF_01', 'Logic is more important than emotions.', 'TF', 1, 3),
  (18, 'TF_02', 'I make objective decisions.', 'TF', 1, 7),
  (19, 'TF_03', 'Facts matter more than feelings.', 'TF', 1, 11),
  (20, 'TF_04', 'I can provide direct criticism.', 'TF', 1, 15),
  (21, 'TF_05', 'I prioritize fairness over compassion.', 'TF', 1, 19),
  (22, 'TF_06', 'I analyze before reacting.', 'TF', 1, 23),
  (23, 'TF_07', 'I remain calm during conflict.', 'TF', 1, 27),
  (24, 'TF_08', 'I separate emotions from decisions.', 'TF', 1, 31),
  (25, 'JP_01', 'I prefer detailed plans.', 'JP', 1, 4),
  (26, 'JP_02', 'I dislike last-minute changes.', 'JP', 1, 8),
  (27, 'JP_03', 'I organize my schedule carefully.', 'JP', 1, 12),
  (28, 'JP_04', 'I finish tasks early.', 'JP', 1, 16),
  (29, 'JP_05', 'I prefer predictable routines.', 'JP', 1, 20),
  (30, 'JP_06', 'I like structured environments.', 'JP', 1, 24),
  (31, 'JP_07', 'I make decisions quickly.', 'JP', 1, 28),
  (32, 'JP_08', 'I enjoy setting goals.', 'JP', 1, 32);

-- -----------------------------------------------------------------------------
-- Seed: 5 Likert options per question (160 rows)
-- -----------------------------------------------------------------------------
INSERT INTO `personality_question_options`
  (`question_id`, `option_key`, `option_text`, `score_direction`, `score_value`, `display_order`)
VALUES
  (1, 'STRONGLY_AGREE', 'Strongly Agree', 'E', 2, 1),
  (1, 'AGREE', 'Agree', 'E', 1, 2),
  (1, 'NEUTRAL', 'Neutral', 'E', 0, 3),
  (1, 'DISAGREE', 'Disagree', 'I', 1, 4),
  (1, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'I', 2, 5),
  (2, 'STRONGLY_AGREE', 'Strongly Agree', 'E', 2, 1),
  (2, 'AGREE', 'Agree', 'E', 1, 2),
  (2, 'NEUTRAL', 'Neutral', 'E', 0, 3),
  (2, 'DISAGREE', 'Disagree', 'I', 1, 4),
  (2, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'I', 2, 5),
  (3, 'STRONGLY_AGREE', 'Strongly Agree', 'E', 2, 1),
  (3, 'AGREE', 'Agree', 'E', 1, 2),
  (3, 'NEUTRAL', 'Neutral', 'E', 0, 3),
  (3, 'DISAGREE', 'Disagree', 'I', 1, 4),
  (3, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'I', 2, 5),
  (4, 'STRONGLY_AGREE', 'Strongly Agree', 'E', 2, 1),
  (4, 'AGREE', 'Agree', 'E', 1, 2),
  (4, 'NEUTRAL', 'Neutral', 'E', 0, 3),
  (4, 'DISAGREE', 'Disagree', 'I', 1, 4),
  (4, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'I', 2, 5),
  (5, 'STRONGLY_AGREE', 'Strongly Agree', 'E', 2, 1),
  (5, 'AGREE', 'Agree', 'E', 1, 2),
  (5, 'NEUTRAL', 'Neutral', 'E', 0, 3),
  (5, 'DISAGREE', 'Disagree', 'I', 1, 4),
  (5, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'I', 2, 5),
  (6, 'STRONGLY_AGREE', 'Strongly Agree', 'E', 2, 1),
  (6, 'AGREE', 'Agree', 'E', 1, 2),
  (6, 'NEUTRAL', 'Neutral', 'E', 0, 3),
  (6, 'DISAGREE', 'Disagree', 'I', 1, 4),
  (6, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'I', 2, 5),
  (7, 'STRONGLY_AGREE', 'Strongly Agree', 'E', 2, 1),
  (7, 'AGREE', 'Agree', 'E', 1, 2),
  (7, 'NEUTRAL', 'Neutral', 'E', 0, 3),
  (7, 'DISAGREE', 'Disagree', 'I', 1, 4),
  (7, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'I', 2, 5),
  (8, 'STRONGLY_AGREE', 'Strongly Agree', 'E', 2, 1),
  (8, 'AGREE', 'Agree', 'E', 1, 2),
  (8, 'NEUTRAL', 'Neutral', 'E', 0, 3),
  (8, 'DISAGREE', 'Disagree', 'I', 1, 4),
  (8, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'I', 2, 5),
  (9, 'STRONGLY_AGREE', 'Strongly Agree', 'S', 2, 1),
  (9, 'AGREE', 'Agree', 'S', 1, 2),
  (9, 'NEUTRAL', 'Neutral', 'S', 0, 3),
  (9, 'DISAGREE', 'Disagree', 'N', 1, 4),
  (9, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'N', 2, 5),
  (10, 'STRONGLY_AGREE', 'Strongly Agree', 'S', 2, 1),
  (10, 'AGREE', 'Agree', 'S', 1, 2),
  (10, 'NEUTRAL', 'Neutral', 'S', 0, 3),
  (10, 'DISAGREE', 'Disagree', 'N', 1, 4),
  (10, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'N', 2, 5),
  (11, 'STRONGLY_AGREE', 'Strongly Agree', 'S', 2, 1),
  (11, 'AGREE', 'Agree', 'S', 1, 2),
  (11, 'NEUTRAL', 'Neutral', 'S', 0, 3),
  (11, 'DISAGREE', 'Disagree', 'N', 1, 4),
  (11, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'N', 2, 5),
  (12, 'STRONGLY_AGREE', 'Strongly Agree', 'S', 2, 1),
  (12, 'AGREE', 'Agree', 'S', 1, 2),
  (12, 'NEUTRAL', 'Neutral', 'S', 0, 3),
  (12, 'DISAGREE', 'Disagree', 'N', 1, 4),
  (12, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'N', 2, 5),
  (13, 'STRONGLY_AGREE', 'Strongly Agree', 'S', 2, 1),
  (13, 'AGREE', 'Agree', 'S', 1, 2),
  (13, 'NEUTRAL', 'Neutral', 'S', 0, 3),
  (13, 'DISAGREE', 'Disagree', 'N', 1, 4),
  (13, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'N', 2, 5),
  (14, 'STRONGLY_AGREE', 'Strongly Agree', 'S', 2, 1),
  (14, 'AGREE', 'Agree', 'S', 1, 2),
  (14, 'NEUTRAL', 'Neutral', 'S', 0, 3),
  (14, 'DISAGREE', 'Disagree', 'N', 1, 4),
  (14, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'N', 2, 5),
  (15, 'STRONGLY_AGREE', 'Strongly Agree', 'S', 2, 1),
  (15, 'AGREE', 'Agree', 'S', 1, 2),
  (15, 'NEUTRAL', 'Neutral', 'S', 0, 3),
  (15, 'DISAGREE', 'Disagree', 'N', 1, 4),
  (15, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'N', 2, 5),
  (16, 'STRONGLY_AGREE', 'Strongly Agree', 'S', 2, 1),
  (16, 'AGREE', 'Agree', 'S', 1, 2),
  (16, 'NEUTRAL', 'Neutral', 'S', 0, 3),
  (16, 'DISAGREE', 'Disagree', 'N', 1, 4),
  (16, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'N', 2, 5),
  (17, 'STRONGLY_AGREE', 'Strongly Agree', 'T', 2, 1),
  (17, 'AGREE', 'Agree', 'T', 1, 2),
  (17, 'NEUTRAL', 'Neutral', 'T', 0, 3),
  (17, 'DISAGREE', 'Disagree', 'F', 1, 4),
  (17, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'F', 2, 5),
  (18, 'STRONGLY_AGREE', 'Strongly Agree', 'T', 2, 1),
  (18, 'AGREE', 'Agree', 'T', 1, 2),
  (18, 'NEUTRAL', 'Neutral', 'T', 0, 3),
  (18, 'DISAGREE', 'Disagree', 'F', 1, 4),
  (18, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'F', 2, 5),
  (19, 'STRONGLY_AGREE', 'Strongly Agree', 'T', 2, 1),
  (19, 'AGREE', 'Agree', 'T', 1, 2),
  (19, 'NEUTRAL', 'Neutral', 'T', 0, 3),
  (19, 'DISAGREE', 'Disagree', 'F', 1, 4),
  (19, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'F', 2, 5),
  (20, 'STRONGLY_AGREE', 'Strongly Agree', 'T', 2, 1),
  (20, 'AGREE', 'Agree', 'T', 1, 2),
  (20, 'NEUTRAL', 'Neutral', 'T', 0, 3),
  (20, 'DISAGREE', 'Disagree', 'F', 1, 4),
  (20, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'F', 2, 5),
  (21, 'STRONGLY_AGREE', 'Strongly Agree', 'T', 2, 1),
  (21, 'AGREE', 'Agree', 'T', 1, 2),
  (21, 'NEUTRAL', 'Neutral', 'T', 0, 3),
  (21, 'DISAGREE', 'Disagree', 'F', 1, 4),
  (21, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'F', 2, 5),
  (22, 'STRONGLY_AGREE', 'Strongly Agree', 'T', 2, 1),
  (22, 'AGREE', 'Agree', 'T', 1, 2),
  (22, 'NEUTRAL', 'Neutral', 'T', 0, 3),
  (22, 'DISAGREE', 'Disagree', 'F', 1, 4),
  (22, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'F', 2, 5),
  (23, 'STRONGLY_AGREE', 'Strongly Agree', 'T', 2, 1),
  (23, 'AGREE', 'Agree', 'T', 1, 2),
  (23, 'NEUTRAL', 'Neutral', 'T', 0, 3),
  (23, 'DISAGREE', 'Disagree', 'F', 1, 4),
  (23, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'F', 2, 5),
  (24, 'STRONGLY_AGREE', 'Strongly Agree', 'T', 2, 1),
  (24, 'AGREE', 'Agree', 'T', 1, 2),
  (24, 'NEUTRAL', 'Neutral', 'T', 0, 3),
  (24, 'DISAGREE', 'Disagree', 'F', 1, 4),
  (24, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'F', 2, 5),
  (25, 'STRONGLY_AGREE', 'Strongly Agree', 'J', 2, 1),
  (25, 'AGREE', 'Agree', 'J', 1, 2),
  (25, 'NEUTRAL', 'Neutral', 'J', 0, 3),
  (25, 'DISAGREE', 'Disagree', 'P', 1, 4),
  (25, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'P', 2, 5),
  (26, 'STRONGLY_AGREE', 'Strongly Agree', 'J', 2, 1),
  (26, 'AGREE', 'Agree', 'J', 1, 2),
  (26, 'NEUTRAL', 'Neutral', 'J', 0, 3),
  (26, 'DISAGREE', 'Disagree', 'P', 1, 4),
  (26, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'P', 2, 5),
  (27, 'STRONGLY_AGREE', 'Strongly Agree', 'J', 2, 1),
  (27, 'AGREE', 'Agree', 'J', 1, 2),
  (27, 'NEUTRAL', 'Neutral', 'J', 0, 3),
  (27, 'DISAGREE', 'Disagree', 'P', 1, 4),
  (27, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'P', 2, 5),
  (28, 'STRONGLY_AGREE', 'Strongly Agree', 'J', 2, 1),
  (28, 'AGREE', 'Agree', 'J', 1, 2),
  (28, 'NEUTRAL', 'Neutral', 'J', 0, 3),
  (28, 'DISAGREE', 'Disagree', 'P', 1, 4),
  (28, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'P', 2, 5),
  (29, 'STRONGLY_AGREE', 'Strongly Agree', 'J', 2, 1),
  (29, 'AGREE', 'Agree', 'J', 1, 2),
  (29, 'NEUTRAL', 'Neutral', 'J', 0, 3),
  (29, 'DISAGREE', 'Disagree', 'P', 1, 4),
  (29, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'P', 2, 5),
  (30, 'STRONGLY_AGREE', 'Strongly Agree', 'J', 2, 1),
  (30, 'AGREE', 'Agree', 'J', 1, 2),
  (30, 'NEUTRAL', 'Neutral', 'J', 0, 3),
  (30, 'DISAGREE', 'Disagree', 'P', 1, 4),
  (30, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'P', 2, 5),
  (31, 'STRONGLY_AGREE', 'Strongly Agree', 'J', 2, 1),
  (31, 'AGREE', 'Agree', 'J', 1, 2),
  (31, 'NEUTRAL', 'Neutral', 'J', 0, 3),
  (31, 'DISAGREE', 'Disagree', 'P', 1, 4),
  (31, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'P', 2, 5),
  (32, 'STRONGLY_AGREE', 'Strongly Agree', 'J', 2, 1),
  (32, 'AGREE', 'Agree', 'J', 1, 2),
  (32, 'NEUTRAL', 'Neutral', 'J', 0, 3),
  (32, 'DISAGREE', 'Disagree', 'P', 1, 4),
  (32, 'STRONGLY_DISAGREE', 'Strongly Disagree', 'P', 2, 5);
